### ISSUE TITLE
Newbie Questions about format of the output files recorded in Module 4

### ISSUE THREAD

**Issue by CraigAlanFriedman** [kylemath/EEGEdu#147]
I would have assumed that:

1.     timestamps are milliseconds since 1/1/1970, (GMT?),

2.     (the raw setting) epoch duration is the number of sampling points in an epoch,

3.     an epoch corresponds to a row in the .csv file that is generated,

4.     (the raw setting) sampling points between epoch onsets is the number of sampling points before a new epoch begins, and

5.     the column headings indicate the number of milliseconds past the timestamp of an epoch (row timestamp).

 

But the .csv file produced is not what I expected to see, so probably I’ve got something wrong.  It seems that

·      the timestamps need not be spaced evenly nor consistently with the column headings,

·      the number of observations for a given channel in an epoch need not consistent with my understanding in 2, above,

·      the number of sampling points between epoch onsets need not be consistent with my understanding in 4 above.

 

I’d expected to see evenly spaced timestamps and column headings consistent with that spacing.

**Comment by kylemath** [comment]
ahh, I see,
this is a tradeoff between plotting settings and saving settings. 
If you go to module 11 and save a file you will see a better way of representing the data.

1. Yes the timestamps of subsequent epochs have some jitter due to all the connection lags

2. I think this is the same issue, sometimes some delay in pulling samples 

3. This is probably the. main source of confusion, each row of this output OVERLAPS with the previous rows, this is way there is a suggestion to make the epoch duration and points between epochs 1, in that case each sample "epoch" will only be one sample, and the next sample will be on the next line (so each column will be the channel values over time). Still the samples may not always be evenly spaced in this case, module 11 saves data in this way

you can interpolate or resample the data to get consistent sampling rates
